### ISSUE TITLE
Wi -Fi does not turn on

### ISSUE THREAD

**Issue by Guber01** [nakhonthai/M17AnalogGateway#11]
After loading version 0.9 after reset, I clamped the BOOOOT button for 3 seconds. After that, the program started and turned on the display. But Fi Fo does not turn on.

**Comment by nakhonthai** [comment]
After upgrade to factory reset by push BOOT button 3s after rx,tx led glow or after power in plug.
You can see wifi AP ssid M17AGate and no password, connect by web browser ip  http://192.168.4.1
