### ISSUE TITLE
Problem with AP M17Hotspot

### ISSUE THREAD

**Issue by sp2ong** [nakhonthai/M17AnalogGateway#2]
I see AP M17Hotspot in the list of WIFI networks, but I check by ping 192.168.4.1 it looks like often AP M17Hotspot freezes

From 192.168.4.2 icmp_seq=45 Destination Host Unreachable
64 bytes from 192.168.4.1: icmp_seq=48 ttl=255 time=4.48 ms
64 bytes from 192.168.4.1: icmp_seq=50 ttl=255 time=123 ms
64 bytes from 192.168.4.1: icmp_seq=51 ttl=255 time=207 ms
64 bytes from 192.168.4.1: icmp_seq=56 ttl=255 time=31.3 ms
From 192.168.4.2 icmp_seq=57 Destination Host Unreachable
From 192.168.4.2 icmp_seq=58 Destination Host Unreachable

so I can not connect to hhtp:/192.168.4.1
Maybe it is a problem of power supply via USB PC ESP32 module

UPDATE: I connect with  external power 5V and connect to the terminal but still have problems with connecting to M17Hotspot AP

When I connect via serial port to ESP32 is displayed the following

ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371 
ets Jun  8 2016 00:22:57

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:10044
load:0x40080400,len:5900
entry 0x400806ac
[E][esp32-hal-misc.c:89] enableCore0WDT(): Failed to add Core 0 IDLE task to WDT
Load configure!
Create CODEC2_1600 : nsam=320 ,nbit=64 ,nbyte=8
                                               Create CODEC2_3200 : nsam=160 ,nbit=64 ,nbyte=8
                                                                                              Task Network has been start
Task DSP has been start
Access point running. IP address: 192.168.4.1
WiFi Connecting..
..............................Failed. Will retry...

**Comment by kc1awv** [comment]
I'm having the same issue, also with a WDT timeout. Not sure if this is related.

`rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:10124
load:0x40080400,len:5856
entry 0x400806a8
[E][esp32-hal-misc.c:89] enableCore0WDT(): Failed to add Core 0 IDLE task to WDT
Load configure!
Create CODEC2_1600 : nsam=320 ,nbit=64 ,nbyte=8
Create CODEC2_3200 : nsam=160 ,nbit=64 ,nbyte=8
Task Network has been start
Task DSP has been start
Access point running. IP address: 192.168.4.1
WiFi Connecting..
..............................Failed. Will retry...
E (30778) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
E (30778) task_wdt:  - loopTask (CPU 1)
E (30778) task_wdt: Tasks currently running:
E (30778) task_wdt: CPU 0: tiT
E (30778) task_wdt: CPU 1: IDLE1
E (30778) task_wdt: Aborting.
abort() was called at PC 0x40148120 on core 0

ELF file SHA256: 0000000000000000

Backtrace: 0x40088d58:0x3ffbfc10 0x40088fd5:0x3ffbfc30 0x40148120:0x3ffbfc50 0x4008746d:0x3ffbfc70 0x4000bfed:0x3ffd9f70 0x4008b159:0x3ffd9f80 0x4008d0ff:0x3ffd9fa0 0x4008d752:0x3ffd9fc0 0x4008210d:0x3ffd9fe0 0x4008213e:0x3ffda000 0x40086e45:0x3ffda020 0x4000beaf:0x3ffda040 0x40129134:0x3ffda060 0x4012919f:0x3ffda080 0x40129202:0x3ffda0a0 0x401292c2:0x3ffda0c0 0x40129422:0x3ffda0e0 0x401292a1:0x3ffda100 0x401294a8:0x3ffda120 0x401351c8:0x3ffda140 0x40089fe6:0x3ffda170

Rebooting...`

**Comment by wgaylord** [comment]
I also observed this, I manually set the default and forced it to set the eeprom to it on my board to use this.

**Comment by sp2ong** [comment]
Hi,
I try using this with change default values but my local home WFI router required authmode WIFI_AUTH_WPA2_PSK so I can not connect with fixed default SSID and password WIFI to local AP.

**Comment by sp2ong** [comment]
I use in main.cpp simple code and works nice:

#include <WiFi.h>
// Replace with your network credentials (STATION)
const char* ssid = "REPLACE_WITH_YOUR_SSID";
const char* password = "REPLACE_WITH_YOUR_PASSWORD";
void initWiFi() {
  WiFi.mode(WIFI_STA);
  WiFi.begin(ssid, password);
  Serial.print("Connecting to WiFi ..");
  while (WiFi.status() != WL_CONNECTED) {
    Serial.print('.');
    delay(1000);
  }
  Serial.println(WiFi.localIP());
}
void setup() {
  Serial.begin(115200);
  initWiFi();
  Serial.print("RRSI: ");
  Serial.println(WiFi.RSSI());
}
void loop() {
  // put your main code here, to run repeatedly:
}
It seems that part of the code for void taskNetwork (void * pvParameters) responsible for the WIFI connection should be written a little differently because the original code does not work for me

**Comment by nakhonthai** [comment]
Bug from ADC ISR  with WiFi to reboot.

**Comment by sp2ong** [comment]
Atten, thank you for the information so I suppose you know how to solve this :-) and we can back to the game with M17AnalogGateway

**Comment by sp2ong** [comment]
Hi Atten, 
I read that some recommend call WiFi.begin only once. Then get the status using WiFi.status:

if (WiFi.status() != WL_CONNECTED) 

or replace check status with

if (WiFi.localIP().toString() == "0.0.0.0")

**Comment by nakhonthai** [comment]
WiFi.status is check wifi auth connection.
WiFi.localIP Check DHCP from router or AP.

**Comment by sp2ong** [comment]
Hi Atten,

The new code looks works nice, many thanks:

ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:10044
load:0x40080400,len:5900
entry 0x400806ac
v_ref routed to GPIO 25
                       [E][esp32-hal-misc.c:89] enableCore0WDT(): Failed to add Core 0 IDLE task to WDT
Load configure!
Create CODEC2_1600 : nsam=320 ,nbit=64 ,nbyte=8
                                               Create CODEC2_3200 : nsam=160 ,nbit=64 ,nbyte=8
                                                                                              Task Network has been start
Task DSP has been start
Access point running. IP address: 192.168.4.1
WiFi Connecting..
....WiFi connected
Host IP address: 192.168.1.33
### You can config by websevice ###
WiFi AP URL: http://192.168.4.1
WiFi STA URL: http://192.168.1.33
Ping Gateway to 192.168.1.1
Ping Success!!
M17 Connecting..
CONNECTING Host: 77.55.209.188:17000 Ping: 0
PING Host: 77.55.209.188:17000 Ping: 1
PING Host: 77.55.209.188:17000 Ping: 2

**Comment by sp2ong** [comment]
I am not sure what is one warring:

[E][esp32-hal-misc.c:89] enableCore0WDT(): Failed to add Core 0 IDLE task to WDT

**Comment by nakhonthai** [comment]
Watch dog for CORE 0 it can't enable begin in setup() function.

**Comment by sp2ong** [comment]
Hmm,

During the first upload of the new version v0.2 I changed the default setting in main.cpp, which are saved in the EPROM and accidentally deleted the lines
         sprintf (config.wifi_ap_ssid, "M17Analog");
and everything works fine but when I put the lines back on
         sprintf (config.wifi_ap_ssid, "M17Analog");
the behavior of the M17Analoggateway is the same as in version 0.1, i.e. it is not possible to connect to the WIFI AP and ESP does not connect to the local AP

I checked it 2 times compiling the firmware and when it is removed line
      sprintf (config.wifi_ap_ssid, "M17Analog");
everything works properly after WIFI and when I remove it and check the settings via the website, the WiFi AP SSID contains the last 8 letters of config.wifi_pass

**Comment by nakhonthai** [comment]
You can checked remove "WiFi AP Enable" for AP close in the webservice tab Setting->WiFi Network or Fix default config to config.wifi_mode = WIFI_STA;

**Comment by sp2ong** [comment]
Thanks, but it is interesting why when I remove from main.cpp line 

sprintf (config.wifi_ap_ssid, "M17Analog"); 

and change line 

WiFi.softAP(config.wifi_ap_ssid, config.wifi_ap_pass); 

to

WiFi.softAP("M17Analog", config.wifi_ap_pass); 

WIFI works  and AP and STA too on ESP32

but when is original code with sprintf (config.wifi_ap_ssid, "M17Analog");  WIFI not working on console only display

WiFi Connecting..
..............................Failed. Will retry...
WiFi Connecting..
..............................Failed. Will retry...

**Comment by nakhonthai** [comment]
WiFi AP(Access Point) mode for connect to config wifi client or config other.
WiFi Connecting status in serial terminal is wifi client connect to router status,it not WiFi AP status.

**Comment by sp2ong** [comment]
Ok, but interesting is why when is in main.cpp line sprintf (config.wifi_ap_ssid, "M17Analog"); broken WIFI Client connection
but it maybe it is my local problem and but maybe others who are using the latest v0.2 don't have this problem
