### ISSUE TITLE
Incorrect location for bootloader.bin ?

### ISSUE THREAD

**Issue by sp2ong** [nakhonthai/M17AnalogGateway#3]
In wiki and on main page the project on github is 
_2.Download firmware and open the program ESP32 DOWNLOAD TOOL, set it in the firmware upload program, set the firmware to M17Hotspot_Vxx.bin, location 0x10000 and partitions.bin at 0x8000 and bootloader.bin at 0x10000 and boot.bin at 0xe000,_ 

It looks is the wrong location for bootloader,bin **0x10000** when I used this value is not working. After looking on different web pages about load programs to ESP32 it looks location for bootloader.bin should be **0x1000**

When I used this location for bootoader.bin AP M17Hotspot is shown in the list available WIFI AP but I can not connect to 192.168.4.1

**Comment by nakhonthai** [comment]
Thank you. False doc in readme, bootloader.bin at 0x1000.

**Comment by sp2ong** [comment]
OK, nice so we can close issue
