### ISSUE TITLE
Add a MEM I2S microphone for the esp32

### ISSUE THREAD

**Issue by jumbo5566** [nakhonthai/M17AnalogGateway#5]
i'm trying this SPH0645 MEM microphone
[https://github.com/atomic14/ICS-43434-breakout-board/tree/main/sketch](https://github.com/atomic14/ICS-43434-breakout-board/tree/main/sketch)

**Comment by nakhonthai** [comment]
You can connect interface external I2S pinout and change to I2S mode.
