### ISSUE TITLE
Issues with Config and size of Wifi SSID and Password Field

### ISSUE THREAD

**Issue by wgaylord** [nakhonthai/M17AnalogGateway#7]
With the current config struct the password for my Wifi is to large to fit into the structure. 

For WEP Wifi access point the max password length is 16 characters and for WPA-PSK/WPA2-PSK the max is 63 characters.

Currently if your password it too long it will partially over write the name of the ESP's own AP with part of your password that doesn't fit.

In addition Wifi access points can have names that are up to 32 characters long. So if your going to change the config struct you might as well fix both potential issues at the same time.

**Comment by sp2ong** [comment]
William,

Thank you for your attention and now I understand why I had a WIFI problem with the AnalogM17Gateway and had to modify the code to make it work. I did not notice that the definition of the password length in the code is max. 16 characters and my passwords are longer than 16 characters

**Comment by wgaylord** [comment]
Looks like this was just fixed in Version 0.9 so I will be closing this.
